### ISSUE TITLE
"Can not connect to cloud"

### ISSUE THREAD

**Issue by banddans** [TheCommCraft/scratchcommunication#3]
I get this error each time I try to connect:

/Users/banddanas/Library/Python/3.12/lib/python/site-packages/scratchcommunication/session.py:75: UserWarning: Couldn't find XToken. Most features will probably still work.
  warnings.warn("Couldn't find XToken. Most features will probably still work.")
Traceback (most recent call last):
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 170, in _connect
    self.websocket.connect(
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_core.py", line 256, in connect
    self.sock, addrs = connect(
                       ^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 151, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 311, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 281, in _wrap_sni_socket
    return context.wrap_socket(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 170, in _connect
    self.websocket.connect(
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_core.py", line 256, in connect
    self.sock, addrs = connect(
                       ^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 151, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 311, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 281, in _wrap_sni_socket
    return context.wrap_socket(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 170, in _connect
    self.websocket.connect(
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_core.py", line 256, in connect
    self.sock, addrs = connect(
                       ^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 151, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 311, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 281, in _wrap_sni_socket
    return context.wrap_socket(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 170, in _connect
    self.websocket.connect(
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_core.py", line 256, in connect
    self.sock, addrs = connect(
                       ^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 151, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 311, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 281, in _wrap_sni_socket
    return context.wrap_socket(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 170, in _connect
    self.websocket.connect(
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_core.py", line 256, in connect
    self.sock, addrs = connect(
                       ^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 151, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 311, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 281, in _wrap_sni_socket
    return context.wrap_socket(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 170, in _connect
    self.websocket.connect(
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_core.py", line 256, in connect
    self.sock, addrs = connect(
                       ^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 151, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 311, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 281, in _wrap_sni_socket
    return context.wrap_socket(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 170, in _connect
    self.websocket.connect(
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_core.py", line 256, in connect
    self.sock, addrs = connect(
                       ^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 151, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 311, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 281, in _wrap_sni_socket
    return context.wrap_socket(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 170, in _connect
    self.websocket.connect(
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_core.py", line 256, in connect
    self.sock, addrs = connect(
                       ^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 151, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 311, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 281, in _wrap_sni_socket
    return context.wrap_socket(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 170, in _connect
    self.websocket.connect(
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_core.py", line 256, in connect
    self.sock, addrs = connect(
                       ^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 151, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 311, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 281, in _wrap_sni_socket
    return context.wrap_socket(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 170, in _connect
    self.websocket.connect(
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_core.py", line 256, in connect
    self.sock, addrs = connect(
                       ^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 151, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 311, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/websocket/_http.py", line 281, in _wrap_sni_socket
    return context.wrap_socket(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/banddanas/Documents/LiClipse Workspace/Platformer share/main.py", line 6, in <module>
    cloud = session.create_cloudconnection(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/scratchcommunication/session.py", line 158, in create_cloudconnection
    return cloud.CloudConnection(project_id=project_id, session=self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 127, in __init__
    self._connect()
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 184, in _connect
    self._connect(retry=retry - 1)
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 184, in _connect
    self._connect(retry=retry - 1)
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 184, in _connect
    self._connect(retry=retry - 1)
  [Previous line repeated 6 more times]
  File "/Users/banddanas/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 181, in _connect
    raise ConnectionError(
ConnectionError: There was an error while connecting to the cloud server.

**Comment by banddans** [comment]
Are you here now?

**Comment by TheCommCraft** [comment]
Hi

**Comment by banddans** [comment]
Yea so how to solve this?

**Comment by TheCommCraft** [comment]
It seems your SSL certificate is failing, but the weird thing is that the same thing should also happen when you use scratchattach

**Comment by banddans** [comment]
What you need a certificate for this?

**Comment by TheCommCraft** [comment]
for the connection to the cloud server

**Comment by TheCommCraft** [comment]
I'll add an option to try connect without certificate when it can't use one

**Comment by banddans** [comment]
Or whats that i thoguht it was a liscenese first

**Comment by TheCommCraft** [comment]
?

**Comment by TheCommCraft** [comment]
There is a certificate to verify that the server is the one you are trying to connect to

**Comment by banddans** [comment]
Tried with tomething simplier now but its still not working.

```python
import scratchcommunication

session = scratchcommunication.Session("banddans", session_id="nono")

cloud = communication_session.create_cloudconnection(
    project_id = "1037074040"
)
```

**Comment by banddans** [comment]
So everybody have a certificate?

**Comment by TheCommCraft** [comment]
Just wait, I'll make a new update soon, then you can download and it should work.

**Comment by TheCommCraft** [comment]
Try updating your scratchcommunication by typing `pip install scratchcommunication>=2.10.4` into your terminal and add allow_no_certificate=True to the function call that creates the cloud socket:

```python
cloud_socket = session.create_cloud_socket(
    project_id = "884190099", 
    security = security,
    allow_no_certificate = True # Add this line
)
```

**Comment by TheCommCraft** [comment]
Is it working?

**Comment by banddans** [comment]
![Skärmavbild 2024-06-14 kl  07 38 26](https://github.com/TheCommCraft/scratchcommunication/assets/172638654/7182ff01-8afe-4200-a1c4-98af83edcf0f)

**Comment by TheCommCraft** [comment]
Try `pip install -U scratchcommunication` and then `pip show scratchcommunication` and send me the output

**Comment by TheCommCraft** [comment]
so?

**Comment by banddans** [comment]
![Skärmavbild 2024-06-17 kl  09 27 47](https://github.com/TheCommCraft/scratchcommunication/assets/172638654/831c1269-02f5-410a-919d-27b1200893bd)

**Comment by banddans** [comment]
Got you real name lol

**Comment by TheCommCraft** [comment]
Just try `pip install --force-reinstall scratch communication`

banddans ***@***.***> schrieb am Mo., 17. Juni 2024, 09:28:

**Comment by banddans** [comment]
![Skärmavbild 2024-06-17 kl  12 39 03](https://github.com/TheCommCraft/scratchcommunication/assets/172638654/3684cfb2-41e9-4719-b8b5-29b176870776)

**Comment by TheCommCraft** [comment]
sorry i meant scratchcomnunication not scratch communication  bad
autocorrect

banddans ***@***.***> schrieb am Mo., 17. Juni 2024, 12:39:

**Comment by banddans** [comment]
Traceback (most recent call last):
  File "/Users/tomcronow/Documents/LiClipse Workspace/Platformer share/main.py", line 6, in <module>
    cloud = communication_session.create_cloudconnection(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomcronow/Library/Python/3.12/lib/python/site-packages/scratchcommunication/session.py", line 158, in create_cloudconnection
    return cloud.CloudConnection(project_id=project_id, session=self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomcronow/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 127, in __init__
    self._connect()
  File "/Users/tomcronow/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 184, in _connect
    self._connect(retry=retry - 1)
  File "/Users/tomcronow/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 184, in _connect
    self._connect(retry=retry - 1)
  File "/Users/tomcronow/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 184, in _connect
    self._connect(retry=retry - 1)
  [Previous line repeated 6 more times]
  File "/Users/tomcronow/Library/Python/3.12/lib/python/site-packages/scratchcommunication/cloud.py", line 181, in _connect
    raise ConnectionError(
ConnectionError: There was an error while connecting to the cloud server.
tomcronow@Snoddass-MBP Platformer share % python3 main.py
/Users/tomcronow/Library/Python/3.12/lib/python/site-packages/scratchcommunication/session.py:75: UserWarning: Couldn't find XToken. Most features will probably still work.
  warnings.warn("Couldn't find XToken. Most features will probably still work.")
Traceback (most recent call last):
  File "/Users/tomcronow/Documents/LiClipse Workspace/Platformer share/main.py", line 6, in <module>
    cloud = communication_session.create_cloudconnection(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tomcronow/Library/Python/3.12/lib/python/site-packages/scratchcommunication/session.py", line 158, in create_cloudconnection
    return cloud.CloudConnection(project_id=project_id, session=self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CloudConnection.__init__() got an unexpected keyword argument 'allow_no_certificate'

**Comment by banddans** [comment]
So I guess i failed downloading the new version :(

**Comment by banddans** [comment]
It looked like this when i downloaded it:

https://github.com/TheCommCraft/scratchcommunication/assets/172638654/5c21cadd-92f9-4bf5-bb46-428453460cf5


https://github.com/TheCommCraft/scratchcommunication/assets/172638654/5c21cadd-92f9-4bf5-bb46-428453460cf5

**Comment by banddans** [comment]
Bottom here if you didn't see it:

![Skärmavbild 2024-06-17 kl  16 00 03](https://github.com/TheCommCraft/scratchcommunication/assets/172638654/1a6aad43-4a86-487f-aa5f-907914eac094)

**Comment by TheCommCraft** [comment]
try `pip install --no-cache --force-reinstall scratchcommunication`

**Comment by banddans** [comment]
Still not working :(((

**Comment by TheCommCraft** [comment]
What did it say?

banddans ***@***.***> schrieb am Mo., 17. Juni 2024, 19:51:

**Comment by TheCommCraft** [comment]
Do you have Python 3.12 or 3.11?

Simon Gilde ***@***.***> schrieb am Mo., 17. Juni 2024, 20:06:

**Comment by banddans** [comment]
3.12 I think

**Comment by TheCommCraft** [comment]
Can you show me the error from installing?

**Comment by TheCommCraft** [comment]
What happens when you try `pip install scratchcomnunication==2.10.6`

**Comment by banddans** [comment]
![Skärmavbild 2024-06-18 kl  09 58 16](https://github.com/TheCommCraft/scratchcommunication/assets/172638654/602593aa-99df-4e3a-813e-7fb3a92d9baf)

**Comment by TheCommCraft** [comment]
Your python or pip is broken. You'd need to reinstall them for it to work.

**Comment by banddans** [comment]
I reinstalled it but I still get the same error.

**Comment by TheCommCraft** [comment]
You reinstalled python?

banddans ***@***.***> schrieb am Mi., 19. Juni 2024, 19:04:

**Comment by TheCommCraft** [comment]
Try these and tell me if one or more install scratchcommunication==2.10.7:
```
pip install -no-cache scratchcommunication==2.10.7
pip install --upgrade --no-cache scratchcommunication
pip install --force-reinstall --no-cache scratchcommunication
pip install git+https://github.com/thecommcraft/scratchcommunication
```
If none of them work, please reply with the errors.

**Comment by banddans** [comment]
Yessss! I managed to connect but the cloud variable does still not change :(

**Comment by TheCommCraft** [comment]
In what way?

banddans ***@***.***> schrieb am Mi., 19. Juni 2024, 20:36:

**Comment by banddans** [comment]
What do you mean? When i try to change a cloud variable it just doesn't change.

**Comment by TheCommCraft** [comment]
Does it show an update in the cloud logs?

banddans ***@***.***> schrieb am Do., 20. Juni 2024, 13:02:

**Comment by TheCommCraft** [comment]
?

**Comment by TheCommCraft** [comment]
Closing as completed. If you get any new errors, you can reopen this issue or create a new one.
